# Generated by Django 2.0.3 on 2018-06-09 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constituency_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MLA',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=40)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Constituency')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('voter_id', models.CharField(max_length=20, unique=True)),
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hashed_password', models.CharField(max_length=40)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Constituency')),
            ],
        ),
    ]
