# Generated by Django 2.0.3 on 2018-06-09 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180609_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='constituency_mla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmla', to='main.MLA'),
        ),
    ]
