# Generated by Django 2.0.3 on 2018-06-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_issue_solution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='desciption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='desciption',
            new_name='description',
        ),
    ]
