# Generated by Django 2.0.3 on 2018-06-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180609_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteCast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('official', models.BooleanField(default=False)),
                ('vote_type', models.PositiveSmallIntegerField()),
                ('vote_id', models.PositiveIntegerField()),
            ],
        ),
    ]
